giftzillaenv/giftzilla/giftzilla/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

from index.views import custom_404_view, custom_500_view

handler404 = custom_404_view

handler500 = custom_500_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('register/', include('register.urls')),
    path('user/', include('user.urls')),
]

giftzillaenv/giftzilla/index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [

    path("", views.home, name="home"),

]

giftzillaenv/giftzilla/register/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'register'

urlpatterns = [

    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("<int:userID>/profileView", views.profileView, name="profileView"),
    path("<int:userID>/<str:emailPin>/email_Verify", views.email_Verify, name="email_Verify")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

giftzillaenv/giftzilla/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [

        path("createRegistry", views.createRegistry, name="createRegistry"),
        path("<int:userID>/regJoin", views.regJoin, name="regJoin"),
        path("<int:userID>/viewreg", views.viewReg, name="viewReg"),
        path("<str:groupPin>/adminReg", views.adminReg, name="adminReg"),
        path("<str:groupPin>/<int:userID>/userGifts", views.userGifts, name="userGifts"),
        path("<str:groupPin>/<int:userID>/viewWishList", views.viewWishList, name="viewWishList"),
        path("<str:groupPin>/<int:userID>/adminWishListView", views.adminWishListView, name="adminWishListView"),
        path("<str:groupPin>/regDelete", views.regDelete, name="regDelete"),
        path("<str:wishID>/wishEdit", views.wishEdit, name="wishEdit"),
        path("<str:groupPin>/<int:userID>/userRegDelete", views.userRegDelete, name="userRegDelete"),
        path("<str:groupPin>/createPairs", views.createPairs, name="createPairs"),
        path("<str:groupPin>/<int:userID>/viewPairWishList", views.viewPairWishList, name="viewPairWishList"),







]

giftzillaenv/giftzilla/giftzilla/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GiftZilla</title>
    <!-- Add Bootstrap CSS (replace with your actual Bootstrap CSS link) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        /* Custom CSS to make navigation links white */
        .nav-link {
            color: white;
        }

    </style>
</head>
<body>
    <header class="bg-primary text-light">
        <div class="container">
            <h1 class="display-4">GiftZilla</h1>
            <p class="lead">Roar Your Gift List To Life!</p>
            <nav class="d-flex justify-content-between align-items-center">
                <ul class="nav">
                    <li class="nav-item"><a class="nav-link" href="{% url 'index:home' %}">Home</a></li>
                    
                </ul>
                <div> <!-- This div will be pushed to the far right -->
                    {% if user.is_authenticated %}
                        <ul class="nav">
                            <li class="nav-item"><a class="nav-link" href="{% url 'user:viewReg' userID=user.id %}">View Registries</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'user:regJoin' userID=user.id %}">Join Registry</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'user:createRegistry' %}">Create Registry</a></li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register:profileView' userID=user.id %}">Welcome {{ user.username }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register:logout' %}">Logout</a>
                            </li>
                        </ul>
                    {% else %}
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register:login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register:register' %}">Sign Up</a>
                            </li>
                        </ul>
                    {% endif %}
                </div>
            </nav>
        </div>
    </header>

   {% block body %}
   {% endblock %}

    

    <footer class="bg-dark text-light mt-5 py-3">

        <p>&copy; Giftzilla</p>
    </footer>

    <!-- Add Bootstrap JavaScript (optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>