giftzillaenv/giftzilla/giftzilla/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

from index.views import custom_404_view, custom_500_view

handler404 = custom_404_view

handler500 = custom_500_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('register/', include('register.urls')),
    path('user/', include('user.urls')),
]

giftzillaenv/giftzilla/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [

        path("createRegistry", views.createRegistry, name="createRegistry"),
        path("<int:userID>/regJoin", views.regJoin, name="regJoin"),
        path("<int:userID>/viewreg", views.viewReg, name="viewReg"),
        path("<str:groupPin>/adminReg", views.adminReg, name="adminReg"),
        path("<str:groupPin>/<int:userID>/userGifts", views.userGifts, name="userGifts"),
        path("<str:groupPin>/<int:userID>/viewWishList", views.viewWishList, name="viewWishList"),
        path("<str:groupPin>/<int:userID>/adminWishListView", views.adminWishListView, name="adminWishListView"),
        path("<str:groupPin>/regDelete", views.regDelete, name="regDelete"),
        path("<str:wishID>/wishEdit", views.wishEdit, name="wishEdit"),
        path("<str:groupPin>/<int:userID>/userRegDelete", views.userRegDelete, name="userRegDelete"),
        path("<str:groupPin>/createPairs", views.createPairs, name="createPairs"),
        path("<str:groupPin>/<int:userID>/viewPairWishList", views.viewPairWishList, name="viewPairWishList"),







]

giftzillaenv/giftzilla/user/models.py
from django.db import models
from register.models import *

Rank = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3')
)
# Create your models here.
class Gift(models.Model):
    groupPin = models.CharField(max_length=5)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    giftUrl = models.CharField(max_length=800, blank=True, null=True)
    giftRank = models.CharField(max_length=1, choices=Rank, blank=True, null=True)

    def __str__(self):
        return f"{self.groupPin} {self.user} {self.giftUrl} {self.giftUrl}"


class Registry(models.Model):
    regPin = models.CharField(max_length=5)
    admin = models.ForeignKey(User, on_delete=models.CASCADE)
    regName = models.CharField(max_length=25, verbose_name="Registry Group Name:")
    urlNumCap = models.IntegerField(default=5, verbose_name="Max Number Of Gift Request:", blank=True, null=True)
    spendLimit = models.IntegerField(blank=True, null=True, verbose_name="Max Spending Limit:")
    notes = models.TextField(blank=True, null=True, verbose_name="Notes")
    regGroupCap = models.IntegerField(blank=True, null=True, verbose_name="Max Number of Group Participants:")

    def __str__(self):
        return f"{self.regPin} {self.admin} {self.urlNumCap} {self.notes} {self.regGroupCap} {self.spendLimit} {self.regName}"

class giftGroups(models.Model):
    groupPin = models.CharField(max_length=5)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    registry = models.ForeignKey(Registry, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.groupPin} {self.user} {self.registry}"
    
# Model to allow users to select a person in their registry they cannot give a gift to such as a spouse. 
class noGive(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='nogive_user')
    noGift = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name='nogive_noGift', verbose_name="User to not pair with:")
    regPin = models.CharField(max_length=5)

    def __str__(self):
        return f"{self.user} {self.noGift} {self.regPin}"
    
class listPair(models.Model):
    giver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='listpair_giver')
    reciever = models.ForeignKey(User, on_delete=models.CASCADE, related_name='listpair_reciever')
    regPin = models.CharField(max_length=5)

    def __str__(self):
        return f"{self.giver} {self.reciever} {self.regPin}"

giftzillaenv/giftzilla/user/forms.py
from django.forms import ModelForm, CharField


from .models import *

class regForm(ModelForm):
    class Meta:
        model = Registry
        fields = "__all__"
        exclude = ["regPin", "admin"]

class giftForm(ModelForm):
    giftUrl = CharField(required=False)
    class Meta:
        model = Gift
        fields = "__all__"
        exclude = ["groupPin", "user"]

class joinForm(ModelForm):
    class Meta:
        model = giftGroups
        fields = "__all__"
        exclude = ["user", "registry"]

class noGiveForm(ModelForm):
    class Meta:
        model = noGive
        fields = "__all__"
        exclude = ["user"]

giftzillaenv/giftzilla/user/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db import IntegrityError, DatabaseError
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.html import format_html
from django.core.mail import send_mail



from .models import *
from .forms import *
from .utils import generate_pin, regPairs

from user.models import *

# Allows an admin to make adjustments to their registry info
@login_required
def adminReg(request, groupPin):

    # Updates registry details
    if request.method == "POST":

        instance = Registry.objects.get(regPin=groupPin)

        instance.regName = request.POST.get("regName")
        instance.urlNumCap = request.POST.get("urlNumCap")
        instance.spendLimit = request.POST.get("spendLimit")
        instance.notes = request.POST.get("notes")
        instance.regGroupCap = request.POST.get("regGroupCap")

        if instance.regGroupCap == '':
            instance.regGroupCap = None

        instance.save()

        return HttpResponseRedirect(reverse('user:adminReg', args=[groupPin]))
    
    # Queries for user admin registry and sends info to template
    else:
        reg = Registry.objects.get(regPin=groupPin)
        reginstance = regForm(instance=reg)

        regPart = giftGroups.objects.filter(groupPin=groupPin)

        try:
            pairs = listPair.objects.filter(regPin=groupPin)
        except ObjectDoesNotExist:
            pairs = None

        return render(request, "user/adminreg.html", {
            "reginstance": reginstance,
            "reg": reg,
            "regPart": regPart,
            "pairs": pairs
        })
    
# Allows an admin to view a wish list from someone who
# has joined their registry.
@login_required
def adminWishListView(request, userID, groupPin):

    gifts = Gift.objects.filter(user=userID, groupPin=groupPin)
    reg = Registry.objects.get(regPin=groupPin)
    try:
        noPair = noGive.objects.get(user=userID, regPin=groupPin)
    except ObjectDoesNotExist:
        noPair = None
    return render(request, "user/adminwishview.html", {
        "reg": reg,
        "gifts": gifts,
        "noPair": noPair
    })

# Allows admin to create pairs
@login_required
def createPairs(request, groupPin):
    
    reg =  Registry.objects.get(regPin=groupPin)
    noPairs = noGive.objects.filter(regPin=groupPin).values_list('user__id', 'noGift__id')
    people = giftGroups.objects.filter(groupPin=groupPin).values_list('user__id', flat=True)

    try:
        pairs = listPair.objects.filter(regPin=groupPin)
    except ObjectDoesNotExist:
        pairs = None

    if request.method ==  "POST":

        if pairs != None:
            pairs.delete()
        # Utils function to create pairs
        j = regPairs(people, noPairs)

        # In the event the function returns None. Handles error.
        if j == None:
            return render(request, "user/createpairs.html", {
                "reg": reg,
                "message": "Not able to make pairs at this time. Please try again."
            })

        # Creates listPair entries for user pairings
        for p in j:

            userFrom = User.objects.get(id=p[0])
            userTo = User.objects.get(id=p[1])

            html_message = format_html(
                f"Hi {userFrom.first_name},<br>"
                f"Your registry admin has created pairs for your registry: {reg.regName}.<br>"
                f"You are paired with {userTo.first_name} {userTo.last_name}.<br>"
                f"Go to <a href='https://giftzilla-test-l62gt.ondigitalocean.app'>GiftZilla</a> and go to View Registries to see your pairing.<br>"
                "<br>"
                "Thanks, <br>"
                "GiftZilla"
            )

            subject = "GiftZilla: Your registry pairing is READY!"
            message = f" { userFrom.first_name }, Your registry admin has created pairins for your registry. Go to GiftZilla and click view registries to see who you are paired with and their gifts."
            send_mail(subject, message=html_message, recipient_list=[userFrom.email], from_email='noreply.giftzilla@gmail.com', html_message=html_message)

            t = listPair.objects.create(giver=userFrom, reciever=userTo, regPin=groupPin)

            try:
                pairs = listPair.objects.filter(regPin=groupPin)
            except ObjectDoesNotExist:
                pairs = None

        return render(request, "user/createpairs.html", {
            "reg": reg,
            "pairs": pairs,
            "message": "Pairs created successfully."
        })
    
    else:
    
        return  render(request, "user/createpairs.html",{
            "reg": reg,
            "pairs": pairs
        })

# Allows a user to create a new registry.
@login_required
def createRegistry(request):

    if request.method == "POST":
        user = request.user

        f = regForm(request.POST)
        if f.is_valid():
            instance =  f.save(commit=False)
            instance.admin = user
            newGroupPin = generate_pin()
            instance.regPin = newGroupPin
            instance.save()

            # Gives user feedback on their unique group pin and info
            regSuccess = Registry.objects.get(regPin=newGroupPin)

            # Admin should be auto added to their own reg.
            joinGroup = giftGroups(user=user, groupPin=newGroupPin, registry=regSuccess)
            joinGroup.save()

        return render(request, "user/regsuccess.html", {
            "regSuccess": regSuccess
        })
    
    else:
        return render(request, "user/createreg.html", {
            "regForm": regForm
        })
    
# Allows an admin to delete an entire registry
@login_required
def regDelete(request, groupPin):
    
    reg = Registry.objects.get(regPin=groupPin)

    if request.method == "POST":

        
        reg.delete()
        userID = request.user.id
        
        return HttpResponseRedirect(reverse('user:viewReg', args=[userID]))

    else:
        return render(request, "user/regdelete.html", {
            "reg": reg
        })

# Allows a user to join a registry.
@login_required
def regJoin(request, userID):

    if request.method == "POST":
    
        user = User.objects.get(id=userID)
        f = joinForm(request.POST)
        if f.is_valid():
            instance = f.save(commit=False)
            instance.user = user
            pin = instance.groupPin

            # Makes sure user doesn't join the same reg twice
            try: 
                exist = giftGroups.objects.get(groupPin=pin, user=user)
                if exist != None:
                    return render(request, 'user/joinreg.html', {
                        "joinForm": joinForm,
                        "message": "You have already joined that registry. Go to View Registries to get more details."
                    })
            
            # If user has not already joined reg user joining can move forward
            except ObjectDoesNotExist:

            # makes sure the registry pre-exist in the data base
                try:
                    instance.registry = Registry.objects.get(regPin=pin)
                    instance.save()
                    return render(request, 'user/joinreg.html', {
                        "message": "Success group joined. Check View Registries to see group."
                    })
                
                except ObjectDoesNotExist:
            
                    return render(request, "user/joinreg.html", {
                        "joinForm": joinForm,
                        "message": "Group does not exist. Try again"
                    })
        
    else:

        return render(request, "user/joinreg.html", {
            "joinForm": joinForm
        })

# Saves user wish list for a registry they are a part of.
@login_required
def userGifts(request, groupPin, userID):

    # Makes sure a logged in user cannot alter another users list
    if userID != request.user.id:
        return render(request, "index/404.html")
    
    # Saves users wish list urls and 
    elif request.method == "POST":
        groupReg = Registry.objects.get(regPin=groupPin)
        user = User.objects.get(id=userID)
        urlCap = groupReg.urlNumCap

        giftForms = []

        for i in range(urlCap):
            form = giftForm(request.POST, prefix=f'gift_form_{i}')
            giftForms.append(form)

        # if not currentGift.exists():
        try:
            if all(form.is_valid() for form in giftForms):
                for form in giftForms:
                    gift = form.save(commit=False)
                    gift.user = user 
                    gift.groupPin = groupReg.regPin
                    gift.save()
        
        # Saves user selection for someone they can't be paired with

            return render(request, "user/usergifts.html", {
                "message": "Wish list saved.",
                "success":  "success",
                "groupReg": groupReg,
                "user": user,
                "giftForms": giftForms,
                })
        
        except TypeError:


            return render(request, "user/usergifts.html", {
            "groupReg": groupReg,
            "user": user,
            "giftForms": giftForms,
            "message": "Something went wrong saving your wish list. Please try again."
        })
    
    else:
        groupReg = Registry.objects.get(regPin=groupPin)
        user = User.objects.get(id=userID)
        urlCap = groupReg.urlNumCap
        regUsers = giftGroups.objects.filter(groupPin=groupPin)

        giftForms = []

        for i in range(urlCap):
            giftForms.append(giftForm(prefix=f'gift_form_{i}'))

        noForm = noGiveForm()
        noForm.fields['noGift'].queryset = regUsers
        
        return render(request, "user/usergifts.html", {

giftzillaenv/giftzilla/giftzilla/templates/user/adminreg.html
<!-- Admin page for reg admins to edit reg information, create new pairs, or delete reg. -->

{% extends 'layout.html' %}

{% block body %}

<div class="container py-2">
    <div class="btn-group mb-2" role="group" aria-label="Page actions">
        <a class="btn btn-primary" href="{% url 'user:viewReg' userID=user.id %}">Back To View Registries</a>
        <a class="btn btn-primary" href="{% url 'user:regDelete' groupPin=reg.regPin %}">Delete Registry</a>
        <a class="btn btn-primary" href="{% url 'user:createPairs' groupPin=reg.regPin %}">Create Registry Pairings</a>
    </div>
</div>

<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ message }}</h5>
            <h5 class="card-text">Admin Registry Info:</h5>

            <form method="post">
                {% csrf_token %}
                {{ reginstance.as_p }}
                <button type="submit" class="btn btn-primary mt-2">Save</button>
            </form>
        </div>
    </div>
</div>

<div class="container mt-4">
    <h5>Registry participants:</h5>
    <div class="list-group">
        {% for part in regPart %}
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <p class="mb-0">Name: {{ part.user.first_name }} {{ part.user.last_name }}</p>
                <a class="btn btn-primary" href="{% url 'user:adminWishListView' groupPin=reg.regPin userID=part.user.id %}">View Gift List</a>
            </div>
        {% endfor %}
    </div>
</div>

<div class="container mt-4">
    <h5>Registry Pairings:</h5>
    <div class="list-group">
        {% for pair in pairs %}
            <div class="list-group-item">
                <p class="mb-0">Giver: {{ pair.giver.first_name }} {{ pair.giver.last_name }}</p>
                <p class="mb-0">Receiver: {{ pair.reciever.first_name }} {{ pair.reciever.last_name }}</p>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/adminwishview.html
<!-- Page displays to admin a reg user gift list. -->

{% extends 'layout.html' %}

{% block body %} 
<div class="container" style="padding: 10px;">
<a class="btn btn-primary px-2" href="{% url 'user:adminReg' groupPin=reg.regPin %}">Back To Group Info</a>
</div>

<div style="padding: 10px;">
<h4 class="text-center">Wish list for {{ gifts.0.user.first_name }} {{ gifts.0.user.last_name }}</h4>
<h4 class="text-center">Registry: {{ reg.regName }}</h4>
<h4 class="text-center">Registry Pin: {{ reg.regPin }}</h4>

</div>

<div class="container mt-4">
    {% for gift in gifts %}
    <div class="border border-3 p-3 mb-4">
            <p>Wish URL: <a target="_blank" href="{{ gift.giftUrl }}">{{ gift.giftUrl }}</a></p>
            <p>Wish Ranking: {{ gift.giftRank }}</p>
    </div>
    {% endfor %}
</div>


{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/createpairs.html
{% extends 'layout.html' %}

{% block body %}
<div class="container py-2">
<a class="btn btn-primary" style="padding-top: 10px;" href="{% url 'user:adminReg' groupPin=reg.regPin %}">Back To Group Info</a>
</div>

<div class="container py-2">
    <div><h5>{{ message }} </h5></div>
</div>

<div class="container mt-4">
    <div class="card mb-4">
        <div class="card-body">
            <h5 class="card-title">Are you sure you are ready to create registry pairings?</h5>
            <p class="card-text">Please make sure the following is complete:</p>
            <ul>
                <li>All members who need to join have joined.</li>
                <li>All members have submitted gifts to their list.</li>
                <li>All members have appropriate none pairings selected. Such as members of their household.</li>
            </ul>
            <p>If all these items have been satisfied, you are ready to pair your registry members.</p>
            <h2>If you have already created pairs, DO NOT create a new set of pairs. This will be a monumental inconvenience to those who have already purchased gifts.</h2>

            <form method="post" action="{% url 'user:createPairs' groupPin=reg.regPin %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Create Pairings</button>
            </form>
        </div>
    </div>

    <div class="mb-4">
        <h4>Current Registry Group Pairings:</h4>
        {% if pairs %}
            {% for pair in pairs %}
                <h6>{{ pair.giver.first_name }} {{ pair.giver.last_name }} is paired and giving to {{ pair.reciever.first_name }} {{ pair.reciever.last_name }}</h6>
            {% endfor %}
        {% else %}
            <p>You currently have no pairings in your registry. Click "Create Pairings."</p>
        {% endif %}
    </div>
</div>
{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/createreg.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">
    <div class="row justify-content-center">
        <h4>Create A New Gift Registry</h4>
        <p>Create your new gift registry by filling out the form below.</p>
        <ul>
            <li>Set a max number of gift request or leave it at 5. Gift request are limited to 10</li>
            <li>Set a max spending limit for group members to spend on gifts.</li>
            <li>Create a note for group members to read such as when the gift exchange will occur or other helpful gift exchange details.</li>
            <li>Set a max number of group participants. Once the group is full no new members will be allowed to join.</li>
        </ul>
    </div>
</div>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <form method="post">
          {% csrf_token %}
          {{ regForm.as_p }}
          <button type="submit" class="btn btn-primary">Create Registry</button>
        </form>
      </div>
    </div>
  </div>
  

{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/regdelete.html
{% extends 'layout.html' %}

{% block body %}

<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Are you sure you want to delete this registry?</h5>
      <p class="card-text">All data will be lost forever.</p>

      <form method="post" action="{% url 'user:regDelete' groupPin=reg.regPin %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete Registry</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/userRegDel.html
{% extends 'layout.html' %}

{% block body %}

<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Are you sure you want to delete this registry?</h5>
      <p class="card-text">All data will be lost forever.</p>

      <form method="post" action="{% url 'user:userRegDelete' userID=user.id groupPin=reg.groupPin %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete Registry</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/usergifts.html
{% extends 'layout.html' %}

{% block body %}

<div>
    <h1>{{ message }}</h1>
</div>
<div class="container">
    <h5>Welcome {{ user.first_name }} to your wish list!</h5>
    <ul>
        <li>Below you can copy and paste links to gifts you would like.</li>
        <li>You can also give a ranking to your top three gifts.</li>
        <li>Your registry admin has assigned a spending limit of ${{ groupReg.spendLimit }}. So please be mindful of that as you input your gifts.</li>
    </ul>
</div>


<div class="container">
    <h5>You're registering a wish list for group: {{ groupReg.regName }}</h5>
    <h5>Group ID: {{ groupReg.regPin }}</h5>
    <h5>Spending Limit: ${{ groupReg.spendLimit }}</h5>
    <h5>Group Admin: {{ groupReg.admin.first_name }} {{ groupReg.admin.last_name }}</h5>
    
    {% if success %}

    <a class="btn btn-primary" href="{% url 'user:viewWishList' groupPin=groupReg.regPin userID=user.id %}">Edit/View Wish List</a>

    {% else %}
    <form method="post">
        {% csrf_token %}
        <ul class="list-group">
            {% for form in giftForms %}
                <li class="list-group-item">
                    {{ form.as_p }}
                </li>
            {% endfor %}
        </ul>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endif %}
</div>

{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/usernopairs.html
{% extends 'layout.html' %}

{% block body %}

<div>
    <h1>{{ message }}</h1>
</div>
<div class="container">
    <h5>Welcome {{ user.first_name }} to your wish list!</h5>
    <ul>
        <li>Below you can make sure users who might not want to be paired together can be excluded from being matched in your registry.</li>
    </ul>
</div>


<div class="container">
    <h5>Registry Group Name: {{ groupReg.regName }}</h5>
    <h5>Group ID: {{ groupReg.regPin }}</h5>
    
    {% if success %}

    <a class="btn btn-primary" href="{% url 'user:viewWishList' groupPin=groupReg.regPin userID=user.id %}">Edit/View Wish List</a>

    {% else %}
    <form method="post">
        {% csrf_token %}
        <br>
        {% for user in regUsers %}
            <label for="user_dropdown" value="{{ user.user.id }}">{{ user.user.first_name }} {{ user.user.last_name }} can't be pair with:</label>
            <select name="user_dropdown" id="user_dropdown" class="form-select">
                <option value="0">None</option>
                {% for user in regUsers %}
                    <option value="{{ user.user.id }}">{{ user.user.first_name }} {{ user.user.last_name }}</option>
                {% endfor %}
            </select>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endif %}
</div>

{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/viewreg.html
<!-- Page displays all registries for user. Including regs the admin and regs they have joined. -->

{% extends 'layout.html' %}

{% block body %}
<div class="container" style="padding: 10px;">
    <div class="row">
        <div class="col">
            <div>
                <h5>Registries You Admin:</h5>
                {% if adminRegs %}
                    {% for admin in adminRegs %}
                        <div class="border border-3 border-gray p-3 m-3">
                            <p class="fw-bold">Registry Name: {{ admin.regName }}</p>
                            <p>Registry Pin: {{ admin.regPin }}</p>
                            <p>Group admin: {{ admin.admin.first_name }} {{ admin.admin.last_name }}</p>
                            <p>Individual Wish/URL Limit: {{ admin.urlNumCap }}</p>
                            <p>Registry Group Limit: {{ admin.regGroupCap }}</p>
                            <p>Registry Notes: {{ admin.notes }}</p>
                            <a class="btn btn-primary" href="{% url 'user:adminReg' groupPin=admin.regPin %}">Edit Group Info</a>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>You currently have no created registries.</p>
                {% endif %}
            </div>
        </div>

        <div class="col">
            <div>
                <h5>Joined Registries:</h5>
                {% if joinedRegs %}
                    {% for join in joinedRegs %}
                        <div class="border border-3 border-gray p-3 m-3">
                            <p class="fw-bold">Registry Name: {{ join.registry.regName }}</p>
                            <p>Registry Pin: {{ join.groupPin }}</p>
                            <p>Wish List Spending Limit: ${{ join.registry.spendLimit }}</p>
                            <p>Registry Notes: {{ join.registry.notes }}</p>

                            {% if join.groupPin in gifts %}
                            <a class="btn btn-primary" href="{% url 'user:viewWishList' groupPin=join.groupPin userID=join.user.id %}">Edit/View Wish List</a>
                            {% else %}
                            <a class="btn btn-primary" href="{% url 'user:userGifts' groupPin=join.groupPin userID=join.user.id %}">Submit Your Wishlist</a>
                            {% endif %}

                            {% if join.groupPin in pairings %}
                            <a class="btn btn-primary" href="{% url 'user:viewPairWishList' groupPin=join.groupPin userID=join.user.id %}">View Pairing Wish List</a>
                            {% else %}
                            {% endif %}

                            

                           
                        </div>
                    {% endfor %}

                {% else %}
                    <p>You currently have no joined registries.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/wishedit.html
{% extends 'layout.html' %}

{% block body %}

<div class="container py-2">
    <a class="btn btn-primary" href="{% url 'user:viewWishList' userID=request.user.id groupPin=gift.groupPin %}">Back To Wish List</a>
</div>

<div class="container d-flex justify-content-center align-items-center min-vh-100">
    <div class="card" style="width: 66%;"> <!-- Adjusted width to approximately 2/3 of the screen -->
        <div class="card-body">
            <h5 class="card-title">{{ message }}</h5>
            <h5 class="card-text">Edit your gift wish:</h5>

            <form method="post">
                {% csrf_token %}
                {{ giftinstance.as_p }}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

giftzillaenv/giftzilla/giftzilla/templates/user/wishlist.html
<!-- Allows user to see their wish list for a registry, make edits to gifts,
and delete the registry from thier account. -->

{% extends 'layout.html' %}

{% block body %}
<div class="container" style="padding: 10px;">
    <a class="btn btn-primary" href="{% url 'user:viewReg' userID=user.id %}">Back To View Registries</a>
    <a class="btn btn-primary" href="{% url 'user:userRegDelete' userID=user.id groupPin=regDetail.regPin %}">Delete Registry</a>

</div>

<div class="container">
    <h4 class="mt-4">Wish list info for {{ regDetail.regName }} registry:</h4>
    <p>Registry Admin: {{ regDetail.admin.first_name }}  {{ regDetail.admin.last_name }}</p>
    <p>Registry Spending Limit: {{ regDetail.spendLimit }}</p>
    <p>Registry Notes: {{ regDetail.notes }}</p>
</div>

<div class="container mt-4">
    {% for wish in regWishList %}
    <div class="border border-3 p-3 mb-4">
        <p>Wish URL: <a target="_blank" href="{{ wish.giftUrl }}">{{ wish.giftUrl }}</a></p>
        <p>Wish Ranking: {{ wish.giftRank }}</p>
        <button class="btn btn-primary"><a style="color: white;" href="{% url 'user:wishEdit' wishID=wish.id %}">Edit Wish</a></button>
    </div>
    {% endfor %}
</div>
{% endblock %}